# -*- coding: utf-8 -*-
"""Lab_3_Collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-2I-bgk3ghWoMae4RRgTycBLx2Iycm1

Goal 1: Connect to the Raspberry Pi and SNAP
  
  This will be done outside of the Jupyter notebook or py file. We also need to load our documents into the new Raspberry Pi.

Goal 2: Install/Use premade packages/classes onto the Raspberry Pi and Snap
"""

import numpy as np
import matplotlib.pyplot as plt
import astropy
import ugradio #This will only work when running this script on the Raspberry Pi
import snap_spec #This will only work when running this script on the Raspberry Pi

"""Import any packages/classes that we made to collect data

Goal 3: Point the telescope to the first initial position
"""

ifm = ugradio.interf.Interferometer() #create object to control telescopes
ifm.stow() #points at zenith

#determine current location of sun
jd = ugradio.timing.julian_date()
ra, dec = ugradio.coord.sunpos(jd)
#convert coordinate systems
alt, az = ugradio.coord.get_altaz(ra, dec)
#point at the sun
ifm.point(alt, az)

#make sure we give enough time for it to point
if (ifm.get_pointing() != alt, az):
  ifm.point(alt, az)

def sun_point(time):
  snap = snap_spec.UGRadioSnap(host='localhost', stream_1=0, stream_2=1)
  snap.initialize(mode='corr', sample_rate=500)
  ifm = ugradio.interf.Interferometer() #create object to control telescopes
  ifm.stow() #points at zenith
  datafile = np.array([])
  jd_start = #get current julian day
  jd = jd_start
  while jd< jd_start+time:
    jd = #julian day after the loop


    #determine current location of sun
    jd = ugradio.timing.julian_date()
    ra, dec = ugradio.coord.sunpos(jd)
    #convert coordinate systems
    alt, az = ugradio.coord.get_altaz(ra, dec)
    #point at the sun
    ifm.point(alt, az)
    #data collection
    data = snap.read_data()
    datafile = datafile.append(data)
  return datafile

# Instantiate and initialize the spectrometer
snap = snap_spec.UGRadioSnap(host='localhost', stream_1=0, stream_2=1)
snap.initialize(mode='corr', sample_rate=500)

# Collect one cross-correlated spectra
data = snap.read_data()